### ISSUE TITLE
Not working in Elgg 1.9.8

### ISSUE THREAD

**Issue by Yaco** [FxNion/elgg-custom-index-widgets#1]
Hi, the plugin is not working. After activating it I get an empty index, with the following notice on the bottom of the screen:

`WARNING: Deprecated in 1.9: The 'index', 'system' plugin has been deprecated. See elgg_front_page_handler() Called from [#1] /srv/reevo-web/www/red/index.php:22`

Any help?

**Comment by FxNion** [comment]
A this time, the plugins works until ~~1.9.6~~ ~~1.9.7~~ 1.9.8. 
I will take a look and upgrade for next releases.(1.10, 1.11,...)

**Comment by FxNion** [comment]
I tried to reproduce your issue with the 1.9.8 picked on github. I had to reactivate the custom_index_widget in order to make it run, but i didn't have any warning message and the index page shows correctly.

Using Google with your warning message, it seems that the error could belong to the **custom_index** plugin, not the **custom_index_widget** one.

See here may be help: https://community.elgg.org/discussion/view/1846396/what-is-the-correct-way-to-customize-the-index-page-in-elgg-19
